import {
  CandidateStatus,
  CandidateSource,
  Gender,
  EducationLevel,
  AvatarColor,
  Area,
} from './enums'

/**
 * Danh sách ứng viên - Dữ liệu mẫu
 */
export const candidatesData = [
  {
    id: 1,
    phone: '0911650118',
    source: CandidateSource.WEBSITE,
    fullName: 'Dương Lâm Anh',
    email: 'duonglam.anh@gmail.com',
    campaign: '',
    position: 'Nhân viên quản lý',
    job: 'Nhân viên quản lý',
    status: CandidateStatus.HIRED,
    rating: 5,
    dateApplied: '01/12/2025',
    educationLevel: EducationLevel.BACHELOR,
    educationPlace: 'Đại học Kinh tế Quốc dân',
    major: 'Quản trị kinh doanh',
    recentWorkplace: 'Công ty TNHH ABC',
    recruiter: 'Định Nga QTHT',
    usingUnit: '',
    fitProfile: true,
    area: Area.HANOI,
    referrer: '',
    contactInfo: 'Đã liên hệ qua điện thoại',
    potentialWarehouse: false,
    dateOfBirth: '15/03/1995',
    gender: Gender.FEMALE,
    address: '123 Nguyễn Trãi, Thanh Xuân, Hà Nội',
    collaborator: '',
    workplace: 'Công ty TNHH ABC',
    workPeriod: { from: '01/2020', to: '11/2025' },
    jobTitle: 'Nhân viên kinh doanh',
    jobDescription: 'Phụ trách tìm kiếm khách hàng mới, chăm sóc khách hàng cũ',
    avatarColor: AvatarColor.PINK,
    avatarText: 'DA',
    isEmployee: true,
  },
  {
    id: 2,
    phone: '0987410417',
    source: CandidateSource.FACEBOOK,
    fullName: 'Nguyễn Văn Hùng',
    email: 'nguyenvanhung@email.com',
    campaign: 'Tuyển dụng IT Q4/2025',
    position: 'Lập trình viên Frontend',
    job: 'Tuyển lập trình viên Frontend',
    status: CandidateStatus.INTERVIEW,
    rating: 4,
    dateApplied: '05/12/2025',
    educationLevel: EducationLevel.COLLEGE,
    educationPlace: 'Cao đẳng Công nghệ TP.HCM',
    major: 'Công nghệ thông tin',
    recentWorkplace: 'Công ty TNHH XYZ Tech',
    recruiter: 'Trần Minh Anh',
    usingUnit: 'Phòng IT',
    fitProfile: true,
    area: Area.HCM,
    referrer: 'Phạm Văn Long',
    contactInfo: 'Đã gửi email mời phỏng vấn',
    potentialWarehouse: true,
    dateOfBirth: '22/07/1998',
    gender: Gender.MALE,
    address: '456 Lê Lợi, Quận 1, TP. Hồ Chí Minh',
    collaborator: 'Nguyễn Thu Hà',
    workplace: 'Công ty TNHH XYZ Tech',
    workPeriod: { from: '03/2021', to: '12/2025' },
    jobTitle: 'Lập trình viên',
    jobDescription: 'Phát triển và bảo trì các ứng dụng ReactJS và NodeJS',
    avatarColor: AvatarColor.BLUE,
    avatarText: 'NH',
    isEmployee: false,
  },
  {
    id: 3,
    phone: '0961928747',
    source: CandidateSource.LINKEDIN,
    fullName: 'Trần Thị Mai',
    email: 'tranthimai@gmail.com',
    campaign: 'Tuyển dụng Marketing 2025',
    position: 'Trưởng phòng Marketing',
    job: 'Tuyển Trưởng phòng Marketing',
    status: CandidateStatus.SUBMITTED,
    rating: 0,
    dateApplied: '10/12/2025',
    educationLevel: EducationLevel.BACHELOR,
    educationPlace: 'Đại học Đà Nẵng',
    major: 'Marketing',
    recentWorkplace: 'Công ty Cổ phần Marketing 123',
    recruiter: 'Lê Văn Tùng',
    usingUnit: 'Phòng Marketing',
    fitProfile: false,
    area: Area.DANANG,
    referrer: '',
    contactInfo: 'Chưa liên hệ',
    potentialWarehouse: true,
    dateOfBirth: '10/11/1996',
    gender: Gender.FEMALE,
    address: '789 Trần Hưng Đạo, Hải Châu, Đà Nẵng',
    collaborator: '',
    workplace: 'Công ty Cổ phần Marketing 123',
    workPeriod: { from: '06/2019', to: '11/2025' },
    jobTitle: 'Chuyên viên Marketing',
    jobDescription: 'Lập kế hoạch marketing, quản lý fanpage, chạy quảng cáo',
    avatarColor: AvatarColor.ORANGE,
    avatarText: 'TM',
    isEmployee: false,
  },
  {
    id: 4,
    phone: '0123456789',
    source: CandidateSource.TOPCV,
    fullName: 'Phạm Minh Tuấn',
    email: 'phamminhtuan@email.com',
    campaign: 'Tuyển dụng IT Q4/2025',
    position: 'Project Manager',
    job: 'Tuyển Project Manager IT',
    status: CandidateStatus.INTERVIEW_2,
    rating: 5,
    dateApplied: '08/12/2025',
    educationLevel: EducationLevel.MASTER,
    educationPlace: 'Đại học Bách Khoa Hà Nội',
    major: 'Kỹ thuật phần mềm',
    recentWorkplace: 'FPT Software',
    recruiter: 'Định Nga QTHT',
    usingUnit: 'Phòng IT',
    fitProfile: true,
    area: Area.HANOI,
    referrer: '',
    contactInfo: 'Chờ phỏng vấn lần 2',
    potentialWarehouse: false,
    dateOfBirth: '05/01/1992',
    gender: Gender.MALE,
    address: 'Long Biên, Hà Nội',
    collaborator: 'Hoàng Văn Nam',
    workplace: 'FPT Software',
    workPeriod: { from: '01/2018', to: '12/2025' },
    jobTitle: 'Team Lead',
    jobDescription: 'Quản lý team, thiết kế hệ thống, code review',
    avatarColor: AvatarColor.CYAN,
    avatarText: 'PT',
    isEmployee: false,
  },
  {
    id: 5,
    phone: '0909123456',
    source: CandidateSource.WEBSITE,
    fullName: 'Lê Thu Hà',
    email: 'lethuha@gmail.com',
    campaign: 'Tuyển dụng Kế toán 2025',
    position: 'Kế toán trưởng',
    job: 'Tuyển Kế toán trưởng',
    status: CandidateStatus.REVIEWING,
    rating: 3,
    dateApplied: '12/12/2025',
    educationLevel: EducationLevel.BACHELOR,
    educationPlace: 'Đại học Kinh tế TP.HCM',
    major: 'Kế toán',
    recentWorkplace: 'Công ty CP Kế toán ABC',
    recruiter: 'Trần Minh Anh',
    usingUnit: 'Phòng Kế toán',
    fitProfile: false,
    area: Area.HCM,
    referrer: 'Nguyễn Văn Hùng',
    contactInfo: 'Đã nhận CV',
    potentialWarehouse: true,
    dateOfBirth: '18/09/1999',
    gender: Gender.FEMALE,
    address: 'Thủ Đức, TP.HCM',
    collaborator: '',
    workplace: 'Công ty CP Kế toán ABC',
    workPeriod: { from: '07/2021', to: '12/2025' },
    jobTitle: 'Kế toán tổng hợp',
    jobDescription: 'Hạch toán, lập báo cáo tài chính, quyết toán thuế',
    avatarColor: AvatarColor.TEAL,
    avatarText: 'LH',
    isEmployee: false,
  },
]
